### ISSUE TITLE
Causes PC to Freeze on some Fullscreen applications

### ISSUE THREAD

**Issue by yurividal** [mlutfy/hidetopbar#134]
This update works on Gnome 3.24, but causes my PC to freeze when i try to enter a video in fullscreen on chrome. When i disable the extension, fullscreen videos on chrome work fine. Also, maximizing Wine apps also cause PC to freeze when HideTopBar is enabled.

**Comment by tuxor1337** [comment]
For reference (thanks to danslo): https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1681822

**Comment by merlin-it** [comment]
I get  a similar error with fullscreen video in chromium. Sometimes it crashes my X-session completely, sometimes the video will stay fullscreen and is no more controllable, but I can get other programs in the foreground and use a terminal to kill the browser. This happens only when I have hidetopbar enabled.

In the referenced issue a similar behaviour is described, when using a secondary screen.
While I do have some strange problems when switching to fullscreen on my secondary display, it is not the same behaviour as described above. In this case the video is no more controllable when switching back from fullscreen, but I can switch back and control the video there.

So it seems to me these two might be related, because somehow the non-existance of a topbar causes the problem, but the behaviour is not the same.

**Comment by policratus** [comment]
I'm having the same issue described. Every time I try to put Google Chrome on full screen, Gnome completely freezes and it's confirmed that is Hide Top Bar extension is causing this.

**Comment by luizalexandrew** [comment]
I'm going through the same problem using Chrome, when I'm in Maximized Chrome and I put a Youtube video in Fullscreen, it freezes the system and needs to reboot the computer. When Chrome is not maximized, the problem does not occur.

**Comment by luizalexandrew** [comment]
I got the same problem in extension Hide top panel (https://extensions.gnome.org/extension/740/hide-top-panel/) and the problem occurs to me only in Google Chrome, in firefox did not give this problem

**Comment by PhoeniZ** [comment]
I have the same error with gnome 2.23. The sistem crash when I maximize chromium.
Please developer fix it :))

**Comment by ljhui** [comment]
I have the same error with gnome 3.20.4, please fix it!

**Comment by tuxor1337** [comment]
Fixed upstream (see Launchpad link in first comment).
