### ISSUE TITLE
Compatibility with Panel OSD extension

### ISSUE THREAD

**Issue by zypangpang** [mlutfy/hidetopbar#137]
The top bar hides every time there comes a notification, even though the notification doesn't cover any part of the top bar. I think the top bar should not hide when a notification appears. I was wondering whether it can be changed. Thanks.

**Comment by tuxor1337** [comment]
It's intended behaviour that the top bar hides when a notification appears because otherwise the top bar overlaps the notification window. You claim otherwise, would you please provide a screenshot of your setup where one can see that the notification box does indeed not overlap with the top bar?

**Comment by zypangpang** [comment]
Thanks so much for replying. Yes, I think the default notification will surely cover the top bar. But I used the panel osd gnome extension (https://extensions.gnome.org/extension/708/panel-osd/) which can change the position of the notification. So I changed it to be below the top bar, but when the notification appears, the top bar still hides. Could it be tweaked a little? Here is a screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/15856956/26030944/4d7bde9c-3895-11e7-9c08-0ae4b9b44c8e.png)

**Comment by tuxor1337** [comment]
This is a compatibility issue. Probably, the incompatibility is due to the fly-in animation of the message tray that causes the message tray to fly in from the top where the message tray will overlap with the panel at least for a tiny moment. I don't have the time to find a fix, but if somebody is willing to dig into the message tray code, don't hesitate to make a pull request...

**Comment by nunocastromartins** [comment]
Would just like to leave a note here: in my opinion, the top bar hiding on the appearance of a notification seems like a weird "intended behaviour". From a user experience point of view, in the context of a clean desktop, why should the top bar disappear when there is plenty of room for the notification to appear?
I believe that those who have the "intellihide" behaviour active, have it because they want to save screen space **only** when needed.

Wouldn't it be possible to simply provide a margin to the notification area so that it would never overlap the top bar? Something like: `.notification-area {margin-top: current-margin + size-of-the-topbar}`? In case the presence of a margin still triggers the hiding behaviour, maybe change the `position`? It seems possible to solve this with CSS alone, I'm obviously not sure, though.

On another note: maybe change the title of this issue to something like "Prevent topbar from hiding on appearance of a notification"; I was about to create a new issue if I hadn't clicked on this one at random.
