### ISSUE TITLE
Not Working on the desktop 

### ISSUE THREAD

**Issue by Xanaxus** [mlutfy/hidetopbar#227]
![image](https://user-images.githubusercontent.com/53279068/83347421-94edc180-a342-11ea-831d-b764ba70d9ce.png)

**Comment by tuxor1337** [comment]
* Provide a clear description of your issue.
* Provide step-by-step instructions on how to reproduce your issue.
* Provide information about your setup including operating system, GNOME version, Wayland/Xorg, and all GNOME extensions running in parallel.

Otherwise this issue is going to be closed as spam.

**Comment by Xanaxus** [comment]
![image](https://user-images.githubusercontent.com/53279068/83594163-25631680-a57c-11ea-87b6-ead350abf9e9.png)
![image](https://user-images.githubusercontent.com/53279068/83594180-34e25f80-a57c-11ea-8fec-8492bee8d7e3.png)
![image](https://user-images.githubusercontent.com/53279068/83594202-40ce2180-a57c-11ea-800c-ca059967e520.png)

After installing the extension i rebooted my device and i noticed that the top bar is not being hidden on the desktop but works fine on all the other programs and browsers(firefox)
this issue was not faced by me in the previous version

**Comment by tuxor1337** [comment]
There is a preference "Only hide panel when a window takes the space" in the settings. Try deactivating it.

**Comment by Xanaxus** [comment]
Thanks Its working fine now
