### ISSUE TITLE
Add screenshots to the README

### ISSUE THREAD

**Issue by jim4067** [mlutfy/hidetopbar#260]
Hey guys. A feature request that you add screenshots to the redme file

**Comment by tuxor1337** [comment]
If you provide a screenshot, we might add it to the README. But it's not that easy to have a good screenshot of an extension that simply hides something...

**Comment by edgan** [comment]
I used peek to make an animated gif.

![hidetopbar](https://user-images.githubusercontent.com/3506737/115163059-d3c05f00-a05b-11eb-8a78-188dca9d1fca.gif)

**Comment by tuxor1337** [comment]
Thanks, I appreciate your effort. However, I feel like this does not represent very well what this extension does or, how people actually use it. At least, I'm never using it like this. I don't want the bar to be hidden when there is actually no window that occupies the freed space. Furthermore, I usually deactivate the mouse sensitivity because it is distracting when I accidentally touch the top and the bar is shown unexpectedly. Finally, setting the animation times to 0 might be practical for some people, but the overall impression is very flickery and non-smooth.

On a side note, I think that GIF animations are not allowed on extensions.gnome.org, our main dissemination channel.

**Comment by mattdm** [comment]
For what it's worth, I use it in the way portrayed. I want the bar to be hidden except when I call for it (fewer distractions, and it seems more consistent than having it react to windows), and I appreciate the bigger target area for the mouse to bring up the overview. (I'm reconsidering this with GNOME 40, though, since what I really want is an active bottom of the screen now.) I don't have animation times at 0, but I do use Impatience to speed them up.

**Comment by tuxor1337** [comment]
Ah, okay. Don't get me wrong, I don't think that you or somebody else shouldn't use this extensions in this way. I just think that the GIF illustrates a very particular way how to use it. I mentioned my own use case to add a different perspective. I don't want to imply that I'm using it in a way that most people use it.

So, if we want to compose a little screencast that illustrates the functionality of this extension, we should ideally show the preferences window and demonstrate how setting cerrtain options will affect the user experience in different ways.

**Comment by tuxor1337** [comment]
Here is a quick and dirty preview how I would imagine a screencast:

https://user-images.githubusercontent.com/1518387/115284780-6987e700-a14d-11eb-99dd-edb51afcb75b.mp4

**Comment by tuxor1337** [comment]
I included a GIF in the README in 1f42112
