### ISSUE TITLE
Notifications hide bar

### ISSUE THREAD

**Issue by MyNameIsArko** [mlutfy/hidetopbar#275]
Hi,
when bar is visible and notification comes, bar hides itself for duration of the notification and then shows up again. Would it be possible for notifications not to hide bar?
Thanks in advance for response.

**Comment by tuxor1337** [comment]
If the notifications don't hide the bar, the bar will overlap the notifications and you couldn't read them. I think, you don't really want this extension to change, but you want the notifications to show up in a different position (e.g. a few pixels down) where it won't overlap with the top bar. I don't want to implement moving the notifications as part of this extension because that's rather a different kind of functionality. This extension only fiddles with the panel and doesn't touch any other elements of the GNOME UI.

**Comment by MyNameIsArko** [comment]
Strange. Even if I move notifications with panel osd to the bottom of the screen, top bar always hides.

**Comment by tuxor1337** [comment]
Apparently, the PanelOSD extensions uses a non-official API to change the location of notifications. I made sure that Hide Top Bar recognizes that change in 5bf168eacd3bca45eb1a3b035e4ae13a2b3b8298

**Comment by MyNameIsArko** [comment]
Great! Now I'll wait for Gnome 40 compatible version.
