### ISSUE TITLE
Mouse-sensitivity doesn't work when returning from lock screen

### ISSUE THREAD

**Issue by xidddekate** [mlutfy/hidetopbar#278]
Intellihide doesn't work when apps kept opened and I lock the system.
Hope you fix it !!!

**Comment by tuxor1337** [comment]
Please provide:
1. Your operating system (and version).
2. Your version of GNOME.
3. Other GNOME extensions that you use.
4. The number of monitors you use.
5. Step-by-step instructions on how to reproduce your problem.

**Comment by xidddekate** [comment]
1. operating system (and version) = Ubuntu 20.04
  2. Your version of GNOME = 3.36
  3. Other GNOME extensions that you use= Floating dock and GNOME themes
  4.  The number of monitors you use = 1
  5. Step-by-step instructions on how to reproduce your problem =>
                    i) enable the extension and Intellihide (It will work fine). 
                    ii) Now open any app in full screen mode and hit lock button from top bar.
                    iii) unlock the computer and now try to hit the mouse to top bar with minimum pressure that was set in intellihide
                    iv) you won't be able to see the top bar no matter how hard you hit at the top of screen

**Comment by tuxor1337** [comment]
This is not related to intellihide, but to mouse-sensitivity.

I can't reproduce the problem you describe, but I'm on GNOME 3.38 and Fedora 33, with no additional extensions. So, I leave this unconfirmed until somebody else comes up with the same problem.

**Comment by ddnexus** [comment]
It happens here since a few months: Ubuntu 21.04 - GNOME 3.38.5 but it was doing the same even in 20.10 and older GNOME. Not sure weather it's strictly related to screen lock though, It does not happen regularly in a defined way, so I cannot reproduce it at will... it just happens sometimes but it's very annoying.

When it happens I have to wrestle pushing up many times... I can see the bar trying to come down a few pixels, like not having enough strength to come down and going back up as soon I stop pushing up (and even if I am on the top border of the screen).

Sometimes if I go on the bottom of the screen making Dash to Dock appear from hiding and I go immediately up again on the top of the screen, it may fix the problem, but not always. I am not even sure it is a specific interaction with Dash to Dock. It might be just something that Dash to Dock does that removes the condition for it to happen, or it might just be something totally different that I attribute to Dash to Dock but it's not.
