### ISSUE TITLE
Hide top bar not auto-hiding on login

### ISSUE THREAD

**Issue by jacksongoode** [mlutfy/hidetopbar#310]
In order to trigger the hiding at login, one must hover over the bar with a mouse. It should hide initially with no interaction if the top bar is set to hide always.

**Comment by tuxor1337** [comment]
I can't reproduce this on GNOME 40 (Fedora 34). Would you please specify:
* Operating system
* GNOME version
* All enabled GNOME extensions
* Hide Top Bar settings

**Comment by jacksongoode** [comment]
Yes, sorry, should have specified that initially. I'm also on F34, GNOME 40. Hide Top Bar is on its latest and it was installed from GNOME extensions.

**Comment by tuxor1337** [comment]
Hm, I still can't reproduce this. Are you on X11 or on Wayland?

**Comment by jacksongoode** [comment]
> Hm, I still can't reproduce this. Are you on X11 or on Wayland?

Wayland

**Comment by tuxor1337** [comment]
* You also disabled showing the top bar in the overview, right?
* After log-in, GNOME shows the overview (instead of the desktop). Do I understand correctly that you would expect the top bar to be hidden in the overview directly after login, but it isn't? After that, when you switch from the overview to the desktop, does the top bar hide?

**Comment by jacksongoode** [comment]
Nice fix! Looks good to me!
