### ISSUE TITLE
There is an update available for the extension

### ISSUE THREAD

**Issue by logicito** [mlutfy/hidetopbar#314]
Every time I reboot Ubuntu 21.04 I get after the first login a message to update the extension, I logout and login again, the message is gone, then at the next reboot, it will be the same message, I don't think the extension is being updated daily, any advice on how to address this? Thank you

![image](https://user-images.githubusercontent.com/70069626/134235083-ceb9feb5-f0c4-4e1b-8928-6da1a258cdb6.png)

**Comment by tuxor1337** [comment]
Hm, there have been 2 updates in the last two days, and 2 further updates approximately one week ago. Maybe that's the reason for that? The most recent version on extensions.gnome.org is 98.

However, when on Ubuntu, it's probably the best idea to install from apt instead of extensions.gnome.org. See here: https://launchpad.net/ubuntu/+source/gnome-shell-extension-autohidetopbar

**Comment by logicito** [comment]
Well, I think that's it 4 updates in the last few days make sense with my notifications, don't get me wrong, I love updates, they improve the app, and your app is great, so, thank you for keeping it up to date.

**Comment by logicito** [comment]
I just checked the Extensions app and I am on version 98 as well, so all is working well with the extensions.gnome.org

**Comment by tuxor1337** [comment]
Thanks for your feedback!
