### ISSUE TITLE
Error after update hidetopbar

### ISSUE THREAD

**Issue by paulocost4** [mlutfy/hidetopbar#323]
Everthing was fine until the notification about update arrived, after that the extension stopped and a error rise in the fedora 35 gnome 41 wayland.

**Comment by AlejandroC90** [comment]
Have you tried logging out and in? or restarting your pc?, it says right there at the extension's page

**Comment by iago-lito** [comment]
I've just had a compatibility problem here on arch after recent upgrade to gnome 41. Inserting "41" as a new version number in the `metadata.json` file seemed to work fine, but I'm not 100% sure that was the right way to go / the only thing to change.

**Comment by coldtobi** [comment]
disclaimer: I have no idea how Arch is doing things and how you installed the extension), but this repositoriy and as far as I understood it, https://extensions.gnome.org/extension/545/hide-top-bar/ have a version that supports gnome 41 since a while.
If you installed it as some arch package, you probably should file a bug at Arch.

**Comment by rc4-studio** [comment]
Great extension, but after update i get an error message, with the following content: `SyntaxError: expected expression, got '.'`
