### ISSUE TITLE
Error after update hidetopbar

### ISSUE THREAD

**Issue by atos93** [mlutfy/hidetopbar#332]
Everything was fine until the notification about update arrived, after that the extension stopped and a error rise in Ubuntu 20.04 gnome 3.36.9

I tried to:
- restart the pc
- restart gnome [alt + f2 and then type "r"]
- uninstall and reinstall the extension from https://extensions.gnome.org/local/ 

![image](https://user-images.githubusercontent.com/15677399/150673766-354234ab-5ffc-4638-b58d-5228db3dc106.png)

**Comment by rc4-studio** [comment]
Same here

**Comment by rc4-studio** [comment]
I get the following error: `SyntaxError: expected expression, got '.'`

**Comment by tuxor1337** [comment]
Yes, this is due to optional chaining, being introduced only in GNOME 3.38 (https://help.gnome.org/misc/release-notes/3.38/developers.html.en):
https://github.com/rastersoft/hidetopbar/blob/876f19fa11ab14ac5881bb5275d01eb5ef879079/desktopIconsIntegration.js#L152

We solve this by dropping support for 3.34 and 3.36. So, if you are on 3.36 (or lower), please downgrade to the most recent version of Hide Top Bar that supported 3.36 (this should be version 100).
