### ISSUE TITLE
Please tag versions in git repo to match versions on https://extensions.gnome.org/

### ISSUE THREAD

**Issue by coldtobi** [mlutfy/hidetopbar#350]
Hi Mathieu,

Just a suggestion to improve the ability to tell which version on https://extensions.gnome.org/ matches the which revision in the git repo and also let me package the version accordingly -- so that it is easier for people to understand which version they are getting when they e.g install using the package manger.

This would also allow me to package only versions that you deem stable enough for a release -- currently I'm usually packaging the latest commit, and that might possibly not be the best one to release :)

Let me know your thoughts!

Cheers, 
tobi

**Comment by tuxor1337** [comment]
Hi Tobi,

Thanks for your request! You are absolutely right. I will do in the future. Starting from version 104 (the current one on extensions.gnome.org), whenever I upload a release to extensions.gnome.org, I will add a tag here on GitHub accordingly - in the format `extensions.gnome.org-[version number]`.

However, note that I only commit stuff to the "master" branch if it's stable enough to immediately release a version on extensions.gnome.org. In fact, I usually push a new release to extensions.gnome.org as soon as possible after pushing new commits to GitHub. Furthermore, the version numbers on extensions.gnome.org are automatically assigned whenever I upload a new release. So, I don't have control over them and so it's a bit annoying to keep track of that manually. I hope that I don't forget to add the tag in the future. If you notice that I forget to do so, please ping me (e.g. via this issue).

Best,
Thomas

PS: Note that @mlutfy never responds to requests regarding Hide Top Bar. I have been the only maintainer since 2013, and never heard of him since. I tried to reach out to him several times because I would like to move the project to gitlab.gnome.org and because I would like to rename the main branch from `master` to `main`. However, I never got a response from him. Maybe I used the wrong means of communication (e-mail).

**Comment by coldtobi** [comment]
Nice! Thank you very much! (And sorry for my brain messing up with the names ... again... I usually  know that you are the one behind hidetop bar, but when I wrote that above obviously I messed up thing...)
