### ISSUE TITLE
Incompatiblity with TopIcons extension

### ISSUE THREAD

**Issue by giomasce** [mlutfy/hidetopbar#49]
Hi.

If I use HideTopBar and TopIcons at the same time there are problems: after the top bar is hidden and then shown again, icons in TopIcons are not able anymore to receive clicks (with neither left or right mouse button).

I do not know which extension is "faulty" here. But I would like them to work together!

I am using Gnome Shell 3.14 from Debian, but the problem has been there for many versions. I do not know how to provide additional details, but can do it if you tell me how.

Thanks, Giovanni.

**Comment by dffischer** [comment]
This problem still exists on shell version 3.16. TopIcons became a lot more useful since this update, because the new slider for tray icons tends to block a small but important number of pixels in the lower left corner of the screen.

I noticed that despite being nonreactive to clicks, the icons still seem to swallow the event. I cannot drag a maximized window back from the top bar when I try to grab it by an icon instead of an empty space on the panel. Logs show no trace of an error whatsoever.

**Comment by tuxor1337** [comment]
@dffischer Just to point this out again: There's no 3.16 support for hide top bar at the moment.

**Comment by tuxor1337** [comment]
Okay, I can definitely reproduce this now. I don't know why I couldn't one year ago... @evan-phelps instructions are pretty clear.

When scrolling through the review of TopIcons on extensions.gnome.org, you see that this problem has been around for years - already at a time, when the implementation of hide top bar was quite different from today's. The developers of TopIcons never reacted to these reviews and there doesn't seem to be an official bug tracker for TopIcons.

I understand that it would be really nice to have compatibility between the two extensions. But it remains an enhancement in my opinion.

**Comment by dffischer** [comment]
Te me, it seems to work fine, even in combination with the changes from the bottompanel branch. Thank you for the workaround.
